parameters:

services:
    _defaults:
        public: true

    # TWIG
    HBM\TwigExtensionsBundle\Twig\:
        resource: '../../Twig/*'
        exclude:
            - '../../Twig/BaseUrlExtension.php'
            - '../../Twig/ResponsiveSvgExtension.php'
        tags:
            - { name: twig.extension }

    hbm.twig_extensions.baseurl:
        class: HBM\TwigExtensionsBundle\Twig\BaseUrlExtension
        arguments: ['%hbm.twig_extensions.base_url%']
        tags:
            - { name: twig.extension }

    hbm.twig_extension.responsive_svg:
        class: HBM\TwigExtensionsBundle\Twig\ResponsiveSvgExtension
        arguments: ['%hbm.twig_extensions.responsive_svg%', '@logger']
        tags:
            - { name: twig.extension }
