parameters:

services:
    # TWIG
    hbm.twig_extensions.attributes:
        class: HBM\TwigExtensionsBundle\Twig\AttributesExtension
        tags:
            - { name: twig.extension }

    hbm.twig_extensions.bootsrap:
        class: HBM\TwigExtensionsBundle\Twig\BootstrapExtension
        tags:
            - { name: twig.extension }

    hbm.twig_extensions.filter:
        class: HBM\TwigExtensionsBundle\Twig\FilterExtension
        tags:
            - { name: twig.extension }

    hbm.twig_extensions.object:
        class: HBM\TwigExtensionsBundle\Twig\ObjectExtension
        tags:
            - { name: twig.extension }

    hbm.twig_extensions.string:
        class: HBM\TwigExtensionsBundle\Twig\StringExtension
        tags:
            - { name: twig.extension }

    hbm.twig_extensions.datetime:
        class: HBM\TwigExtensionsBundle\Twig\DatetimeExtension
        tags:
            - { name: twig.extension }

    hbm.twig_extensions.baseurl:
        class: HBM\TwigExtensionsBundle\Twig\BaseUrlExtension
        arguments: ["%hbm.twig_extensions.base_url%"]
        tags:
            - { name: twig.extension }

    hbm.twig_extension.responsive_svg:
        class: HBM\TwigExtensionsBundle\Twig\ResponsiveSvgExtension
        arguments: ["@kernel", "%hbm.twig_extensions.responsive_svg%", "@logger"]
        tags:
            - { name: twig.extension }
