parameters:

services:
    _defaults:
        public: true

    # TWIG
    HBM\TwigExtensionsBundle\Twig\Extension\:
        resource: '../src/Twig/Extension/*'
        exclude:
            - '../src/Twig/Extension/BaseUrlExtension.php'
            - '../src/Twig/Extension/ResponsiveSvgExtension.php'
        tags:
            - { name: twig.extension }

    hbm.twig_extensions.baseurl:
        class: HBM\TwigExtensionsBundle\Twig\Extension\BaseUrlExtension
        arguments: ['%hbm.twig_extensions.base_url%']
        tags:
            - { name: twig.extension }

    hbm.twig_extension.responsive_svg:
        class: HBM\TwigExtensionsBundle\Twig\Extension\ResponsiveSvgExtension
        arguments: ['%hbm.twig_extensions.responsive_svg%', '@logger']
        tags:
            - { name: twig.extension }
